version: '3.1'

services:
  fe:
    image: preslavst/sport-world-fe:latest
    container_name: sport-world-fe
    restart: always
    environment:
      REACT_APP_SERVER_HOSTNAME: "http://sport-world:8080"
    ports:
      - "3000:3000"
    depends_on:
      - app

  app:
    image: preslavst/sport-world:amd64-latest
    container_name: sport-world
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - sport_world_db

  db:
    image: mysql
    container_name: sport_world_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d/:ro




